# Generated by Django 6.0.1 on 2026-02-22 07:34

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(help_text='гос. номер', max_length=9, unique=True)),
                ('brand', models.CharField(help_text='марка', max_length=60)),
                ('model', models.CharField(help_text='модель', max_length=60)),
                ('type', models.CharField(help_text='тип', max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(help_text='гос. номер', max_length=9, unique=True)),
                ('brand', models.CharField(help_text='марка')),
                ('model', models.CharField(help_text='модель')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='название', max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FireTruckWaybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(help_text='номер путевого листа', max_length=6, unique=True)),
                ('date', models.DateField(default=datetime.date.today, help_text='дата путевого листа')),
                ('norm_season', models.CharField(choices=[('winter', 'Зима'), ('summer', 'Лето')], help_text='сезон нормы', max_length=10)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизельное топливо')], help_text='тип топлива', max_length=10)),
                ('upon_issuance', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='наличие ГСМ при выдаче, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('total_spent', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='всего израсходовано, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('total_received', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='всего получено (заправки), л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('required_by_norm', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='положено по норме, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('availability_upon_delivery', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='наличие при сдаче, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('savings', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='экономия, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('overrun', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='перерасход, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='fuel.firetruck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FireTruckWaybillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('target', models.CharField(help_text='цель выезда', max_length=255)),
                ('departure_time', models.TimeField(help_text='время убытия')),
                ('arrival_time', models.TimeField(help_text='время прибытия')),
                ('odometer_after', models.PositiveIntegerField(help_text='одометр после возвращения, км', validators=[django.core.validators.MaxValueValidator(999999)])),
                ('time_with_pump', models.PositiveIntegerField(help_text='время работы с насосом, мин', validators=[django.core.validators.MaxValueValidator(999999)])),
                ('time_without_pump', models.PositiveIntegerField(help_text='время работы без насоса, мин', validators=[django.core.validators.MaxValueValidator(999999)])),
                ('fuel_refueled', models.DecimalField(decimal_places=3, default=0, help_text='заправка, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('fuel_used', models.DecimalField(decimal_places=3, help_text='фактически израсходовано, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('fuel_before_departure', models.DecimalField(decimal_places=3, editable=False, help_text='топливо перед выездом, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('odometer_before', models.PositiveIntegerField(editable=False, help_text='одометр перед выездом, км', validators=[django.core.validators.MaxValueValidator(999999)])),
                ('distance_km', models.PositiveIntegerField(editable=False, help_text='пробег, км', validators=[django.core.validators.MaxValueValidator(999999)])),
                ('fuel_on_return', models.DecimalField(decimal_places=3, editable=False, help_text='остаток топлива при возвращении, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('fuel_used_by_distance', models.DecimalField(decimal_places=3, editable=False, help_text='Топливо по пробегу, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('fuel_used_with_pump', models.DecimalField(decimal_places=3, editable=False, help_text='Топливо при работе с насосом, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('fuel_used_without_pump', models.DecimalField(decimal_places=3, editable=False, help_text='Топливо при работе без насоса, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('fuel_used_normal', models.DecimalField(decimal_places=3, editable=False, help_text='израсходовано по норме, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('fire_truck_waybill', models.ForeignKey(help_text='Эксплуатационная карточка', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='fuel.firetruckwaybill')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NormsFireTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('season', models.CharField(choices=[('winter', 'Зима'), ('summer', 'Лето')], help_text='сезон', max_length=10)),
                ('with_pump_norm', models.DecimalField(decimal_places=3, help_text='норма с насосом, л/мин (или др.ед.)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('without_pump_norm', models.DecimalField(decimal_places=3, help_text='норма без насоса, л/мин (или др.ед.)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('km_norm', models.DecimalField(decimal_places=3, help_text='норма по пробегу, л/км', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('date', models.DateField(default=datetime.date.today, help_text='дата утверждения нормы')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='fuel.firetruck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OdometerFuelFireTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('odometer', models.PositiveIntegerField(help_text='показания одометра', validators=[django.core.validators.MaxValueValidator(999999)])),
                ('fuel', models.DecimalField(decimal_places=3, help_text='остаток топлива', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('date', models.DateField(default=datetime.date.today, help_text='дата создания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_fuel_records', to='fuel.firetruck')),
                ('waybill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odometer_fuel_states', to='fuel.firetruckwaybill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NormsPassengerCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('season', models.CharField(choices=[('winter', 'Зима'), ('summer', 'Лето')], help_text='сезон', max_length=10)),
                ('city_norm', models.DecimalField(decimal_places=3, help_text='норма на 1 км по городу, л/км', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('area_norm', models.DecimalField(decimal_places=3, help_text='норма на 1 км по области, л/км', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('date', models.DateField(default=datetime.date.today, help_text='дата утверждения нормы')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='fuel.passengercar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerCarWaybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(help_text='номер путевого листа', max_length=6, unique=True)),
                ('date', models.DateField(default=datetime.date.today, help_text='дата путевого листа')),
                ('norm_season', models.CharField(choices=[('winter', 'Зима'), ('summer', 'Лето')], help_text='сезон нормы', max_length=10)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизельное топливо')], help_text='тип топлива', max_length=10)),
                ('upon_issuance', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='наличие ГСМ при выдаче, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('total_spent', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='всего израсходовано, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('total_received', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='всего получено (заправки), л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('required_by_norm', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='положено по норме, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('availability_upon_delivery', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='наличие при сдаче, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('savings', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='экономия, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('overrun', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='перерасход, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='fuel.passengercar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OdometerFuelPassengerCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('odometer', models.PositiveIntegerField(help_text='показания одометра', validators=[django.core.validators.MaxValueValidator(999999)])),
                ('fuel', models.DecimalField(decimal_places=3, help_text='остаток топлива', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('date', models.DateField(default=datetime.date.today, help_text='дата создания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_fuel_records', to='fuel.passengercar')),
                ('waybill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odometer_fuel_states', to='fuel.passengercarwaybill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerCarWaybillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('target', models.CharField(help_text='цель выезда', max_length=255)),
                ('departure_time', models.TimeField(help_text='время убытия')),
                ('arrival_time', models.TimeField(help_text='время прибытия')),
                ('distance_city_km', models.PositiveIntegerField(help_text='пройдено км по городу', validators=[django.core.validators.MaxValueValidator(999999)])),
                ('distance_area_km', models.PositiveIntegerField(help_text='пройдено км по области', validators=[django.core.validators.MaxValueValidator(999999)])),
                ('fuel_refueled', models.DecimalField(decimal_places=3, default=0, help_text='заправка, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('fuel_used', models.DecimalField(decimal_places=3, help_text='израсходовано топлива, л (фактически)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('odometer_after', models.PositiveIntegerField(editable=False, help_text='одометр после возвращения, км', validators=[django.core.validators.MaxValueValidator(999999)])),
                ('fuel_before_departure', models.DecimalField(decimal_places=3, editable=False, help_text='топливо перед выездом, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('odometer_before', models.PositiveIntegerField(editable=False, help_text='одометр перед выездом, км', validators=[django.core.validators.MaxValueValidator(999999)])),
                ('distance_total_km', models.PositiveIntegerField(editable=False, help_text='всего пройдено км', validators=[django.core.validators.MaxValueValidator(999999)])),
                ('fuel_used_city', models.DecimalField(decimal_places=3, editable=False, help_text='израсходовано по городу, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('fuel_used_area', models.DecimalField(decimal_places=3, editable=False, help_text='израсходовано по области, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('fuel_on_return', models.DecimalField(decimal_places=3, editable=False, help_text='остаток топлива при возвращении, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('fuel_used_normal', models.DecimalField(decimal_places=3, editable=False, help_text='израсходовано по норме, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('passenger_car_waybill', models.ForeignKey(help_text='Путевой лист легкового автомобиля', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='fuel.passengercarwaybill')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('can_use_mobile_booking', models.BooleanField(default=False)),
                ('can_create_users', models.BooleanField(default=False)),
                ('can_delete_users', models.BooleanField(default=False)),
                ('can_update_users', models.BooleanField(default=False)),
                ('view_users', models.BooleanField(default=False)),
                ('can_create_fire_trucks', models.BooleanField(default=False)),
                ('can_delete_fire_trucks', models.BooleanField(default=False)),
                ('can_update_fire_trucks', models.BooleanField(default=False)),
                ('view_fire_trucks', models.BooleanField(default=False)),
                ('can_create_fire_truck_waybils', models.BooleanField(default=False)),
                ('can_delete_fire_truck_waybils', models.BooleanField(default=False)),
                ('can_update_fire_truck_waybils', models.BooleanField(default=False)),
                ('can_download_fire_truck_waybills', models.BooleanField(default=False)),
                ('view_fire_truck_waybils', models.BooleanField(default=False)),
                ('can_create_fire_truck_waybils_record', models.BooleanField(default=False)),
                ('can_delete_fire_truck_waybils_record', models.BooleanField(default=False)),
                ('can_update_fire_truck_waybils_record', models.BooleanField(default=False)),
                ('can_create_fire_truck_norms', models.BooleanField(default=False)),
                ('can_delete_fire_truck_norms', models.BooleanField(default=False)),
                ('can_update_fire_truck_norms', models.BooleanField(default=False)),
                ('view_fire_truck_norms', models.BooleanField(default=False)),
                ('can_download_fire_truck_reports', models.BooleanField(default=False)),
                ('view_fire_truck_reports', models.BooleanField(default=False)),
                ('can_create_passenger_cars', models.BooleanField(default=False)),
                ('can_delete_passenger_cars', models.BooleanField(default=False)),
                ('can_update_passenger_cars', models.BooleanField(default=False)),
                ('view_passenger_cars', models.BooleanField(default=False)),
                ('can_create_passenger_cars_waybills', models.BooleanField(default=False)),
                ('can_delete_passenger_cars_waybills', models.BooleanField(default=False)),
                ('can_update_passenger_cars_waybills', models.BooleanField(default=False)),
                ('can_download_passenger_cars_waybills', models.BooleanField(default=False)),
                ('view_passenger_cars_waybills', models.BooleanField(default=False)),
                ('can_create_passenger_cars_waybils_record', models.BooleanField(default=False)),
                ('can_delete_passenger_cars_waybils_record', models.BooleanField(default=False)),
                ('can_update_passenger_cars_waybils_record', models.BooleanField(default=False)),
                ('can_create_passenger_cars_norms', models.BooleanField(default=False)),
                ('can_delete_passenger_cars_norms', models.BooleanField(default=False)),
                ('can_update_passenger_cars_norms', models.BooleanField(default=False)),
                ('view_passenger_cars_norms', models.BooleanField(default=False)),
                ('can_download_passenger_cars_reports', models.BooleanField(default=False)),
                ('view_passenger_cars_reports', models.BooleanField(default=False)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='fuel.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('login', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('driver_license', models.CharField(max_length=10, null=True, unique=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='fuel.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='passengercarwaybill',
            name='driver',
            field=models.ForeignKey(help_text='водитель', on_delete=django.db.models.deletion.CASCADE, related_name='passenger_car_driver', to='fuel.user'),
        ),
        migrations.AddField(
            model_name='firetruckwaybill',
            name='driver',
            field=models.ForeignKey(help_text='водитель', on_delete=django.db.models.deletion.CASCADE, related_name='fire_truck_driver', to='fuel.user'),
        ),
    ]
