# Generated by Django 6.0.1 on 2026-01-14 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=9, unique=True)),
                ('brand', models.CharField(help_text='марка машины', max_length=30)),
                ('model', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('can_use_mobile_booking', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('from_date', models.DateField()),
                ('for_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FireTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('odometer', models.DecimalField(decimal_places=2, help_text='Текущее показание одометра, км', max_digits=7)),
                ('type', models.CharField(help_text='Тип пожарного автомобиля', max_length=60)),
                ('fuel', models.DecimalField(decimal_places=3, help_text='Показания топлива перед последним выездом, л', max_digits=8)),
                ('winter_km', models.DecimalField(decimal_places=3, help_text='Норма зимой по пробегу, л/км', max_digits=5)),
                ('winter_without_pump', models.DecimalField(decimal_places=3, help_text='Норма зимой без насоса, л/ед.времени', max_digits=5)),
                ('winter_with_pump', models.DecimalField(decimal_places=3, help_text='Норма зимой с насосом, л/ед.времени', max_digits=5)),
                ('summer_km', models.DecimalField(decimal_places=3, help_text='Норма летом по пробегу, л/км', max_digits=5)),
                ('summer_without_pump', models.DecimalField(decimal_places=3, help_text='Норма летом без насоса, л/ед.времени', max_digits=5)),
                ('summer_with_pump', models.DecimalField(decimal_places=3, help_text='Норма летом с насосом, л/ед.времени', max_digits=5)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fire_truck', to='fuel.car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FireTruckWaybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fire_truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='fuel.firetruck')),
                ('waybill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fire_truck_waybill', to='fuel.waybill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FireTruckWaybillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('place_of_work', models.CharField(max_length=255)),
                ('departure_time', models.TimeField()),
                ('return_time', models.TimeField()),
                ('fuel_before_departure', models.DecimalField(decimal_places=3, max_digits=8)),
                ('odometer_before', models.DecimalField(decimal_places=2, max_digits=7)),
                ('odometer_after', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fire_time_with_pump', models.PositiveIntegerField(default=0)),
                ('fire_time_without_pump', models.PositiveIntegerField(default=0)),
                ('training_time_with_pump', models.PositiveIntegerField(default=0)),
                ('training_time_without_pump', models.PositiveIntegerField(default=0)),
                ('shift_change_time_with_pump', models.PositiveIntegerField(default=0)),
                ('shift_change_time_without_pump', models.PositiveIntegerField(default=0)),
                ('other_time_with_pump', models.PositiveIntegerField(default=0)),
                ('other_time_without_pump', models.PositiveIntegerField(default=0)),
                ('fuel_refueled', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('season', models.CharField(choices=[('winter', 'Зимняя норма'), ('summer', 'Летняя норма')], default='summer', max_length=10)),
                ('norm_km', models.DecimalField(decimal_places=3, max_digits=5)),
                ('norm_without_pump', models.DecimalField(decimal_places=3, max_digits=5)),
                ('norm_with_pump', models.DecimalField(decimal_places=3, max_digits=5)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fuel_used_by_distance', models.DecimalField(decimal_places=3, max_digits=8)),
                ('fuel_used_with_pump', models.DecimalField(decimal_places=3, max_digits=8)),
                ('fuel_used_without_pump', models.DecimalField(decimal_places=3, max_digits=8)),
                ('fuel_used_total', models.DecimalField(decimal_places=3, max_digits=8)),
                ('fuel_on_return', models.DecimalField(decimal_places=3, max_digits=8)),
                ('fire_truck_waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='fuel.firetruckwaybill')),
            ],
            options={
                'ordering': ['date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='PassengerCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('odometer', models.DecimalField(decimal_places=2, help_text='Текущее показание одометра, км', max_digits=7)),
                ('fuel', models.DecimalField(decimal_places=3, help_text='Показания топлива перед выездом, л', max_digits=8)),
                ('winter_area', models.DecimalField(decimal_places=3, help_text='Норма зимой по области, л/км', max_digits=5)),
                ('winter_city', models.DecimalField(decimal_places=3, help_text='Норма зимой по городу, л/км', max_digits=5)),
                ('summer_area', models.DecimalField(decimal_places=3, help_text='Норма летом по области, л/км', max_digits=5)),
                ('summer_city', models.DecimalField(decimal_places=3, help_text='Норма летом по городу, л/км', max_digits=5)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_car', to='fuel.car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerCarWaybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('passenger_car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='fuel.passengercar')),
                ('waybill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_car_waybill', to='fuel.waybill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequiredRole',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='required_role_meta', serialize=False, to='fuel.role')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('login', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('driver_license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='fuel.driverlicense')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='fuel.rank')),
                ('role', models.ForeignKey(help_text='Роль (должность) пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='fuel.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerCarWaybillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('fuel_before_departure', models.DecimalField(decimal_places=3, max_digits=8)),
                ('odometer_before', models.DecimalField(decimal_places=2, max_digits=7)),
                ('odometer_after', models.DecimalField(decimal_places=2, max_digits=7)),
                ('distance_city_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('distance_area_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fuel_refueled', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('season', models.CharField(choices=[('winter', 'Зимняя норма'), ('summer', 'Летняя норма')], default='summer', help_text='Какую норму применить (зимняя/летняя)', max_length=10)),
                ('norm_city', models.DecimalField(decimal_places=3, max_digits=5)),
                ('norm_area', models.DecimalField(decimal_places=3, max_digits=5)),
                ('distance_total_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fuel_used_city', models.DecimalField(decimal_places=3, max_digits=8)),
                ('fuel_used_area', models.DecimalField(decimal_places=3, max_digits=8)),
                ('fuel_used_total', models.DecimalField(decimal_places=3, max_digits=8)),
                ('fuel_on_return', models.DecimalField(decimal_places=3, max_digits=8)),
                ('passenger_car_waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='fuel.passengercarwaybill')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_records', to='fuel.user')),
            ],
            options={
                'ordering': ['date', 'driver'],
            },
        ),
        migrations.CreateModel(
            name='RoleSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('main_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_by', to='fuel.role')),
                ('substitute_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='can_substitute_for', to='fuel.role')),
            ],
            options={
                'unique_together': {('main_role', 'substitute_role')},
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='fuel.user')),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='fuel.waybill')),
                ('required_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='fuel.requiredrole')),
            ],
            options={
                'unique_together': {('waybill', 'required_role')},
            },
        ),
    ]
