# Generated by Django 6.0.1 on 2026-01-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='number',
            field=models.PositiveBigIntegerField(default=123),
            preserve_default=False,
        ),
    ]
