# Generated by Django 6.0.1 on 2026-02-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firetruckwaybillrecord',
            name='driving_route',
            field=models.CharField(help_text='Маршрут движения', null=True),
        ),
    ]
