# Generated by Django 6.0.1 on 2026-02-22 08:02

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odometerfuelfiretruck',
            name='car',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='odometer_fuel_records', to='fuel.firetruck'),
        ),
        migrations.AlterField(
            model_name='odometerfuelfiretruck',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='odometerfuelfiretruck',
            name='fuel',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='odometerfuelfiretruck',
            name='odometer',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='odometerfuelpassengercar',
            name='car',
            field=models.ForeignKey(blank=True, help_text='автомобиль', on_delete=django.db.models.deletion.CASCADE, related_name='odometer_fuel_records', to='fuel.passengercar'),
        ),
        migrations.AlterField(
            model_name='odometerfuelpassengercar',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='дата состояния'),
        ),
        migrations.AlterField(
            model_name='odometerfuelpassengercar',
            name='fuel',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='остаток топлива, л', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='odometerfuelpassengercar',
            name='odometer',
            field=models.PositiveIntegerField(blank=True, help_text='показания одометра, км', validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='odometerfuelpassengercar',
            name='waybill',
            field=models.ForeignKey(blank=True, help_text='путевой лист (если указан, данные подтянутся автоматически)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odometer_fuel_states', to='fuel.passengercarwaybill'),
        ),
    ]
