# Generated by Django 6.0.1 on 2026-01-14 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_waybill_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passengercarwaybillrecord',
            options={'ordering': ['date', 'driver_id']},
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='date',
            field=models.DateField(help_text='Дата работы пожарного автомобиля'),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='departure_time',
            field=models.TimeField(help_text='Время выезда автомобиля'),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Пробег за поездку, км', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='fire_truck_waybill',
            field=models.ForeignKey(help_text='Эксплуатационная карточка, к которой относится запись', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='fuel.firetruckwaybill'),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='fuel_before_departure',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Топливо перед выездом, л (автоматически)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='fuel_on_return',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Остаток топлива в баке при возвращении, л', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='fuel_refueled',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Заправлено топлива за время этой записи, л', max_digits=8),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='fuel_used_by_distance',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Топливо по пробегу, л', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='fuel_used_total',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Всего израсходовано топлива, л', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='fuel_used_with_pump',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Топливо при работе с насосом, л', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='fuel_used_without_pump',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Топливо при работе без насоса, л', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='norm_km',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Норма по пробегу, л/км, применённая к записи', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='norm_with_pump',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Норма с насосом, л/ед.времени, применённая к записи', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='norm_without_pump',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Норма без насоса, л/ед.времени, применённая к записи', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='odometer_after',
            field=models.DecimalField(decimal_places=2, help_text='Показание одометра после возвращения, км', max_digits=7),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='odometer_before',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Одометр перед выездом, км (автоматически)', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='place_of_work',
            field=models.CharField(help_text='Наименование и место работы автомобиля', max_length=255),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='return_time',
            field=models.TimeField(help_text='Время возвращения автомобиля'),
        ),
        migrations.AlterField(
            model_name='firetruckwaybillrecord',
            name='season',
            field=models.CharField(choices=[('winter', 'Зимняя норма'), ('summer', 'Летняя норма')], default='summer', help_text='Какую норму применить (зимняя/летняя)', max_length=10),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='date',
            field=models.DateField(help_text='Дата работы легкового автомобиля'),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='distance_area_km',
            field=models.DecimalField(decimal_places=2, help_text='Пробег по области за поездку, км', max_digits=7),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='distance_city_km',
            field=models.DecimalField(decimal_places=2, help_text='Пробег по городу за поездку, км', max_digits=7),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='distance_total_km',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Общий пробег за поездку, км', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='driver',
            field=models.ForeignKey(help_text='Водитель', on_delete=django.db.models.deletion.CASCADE, related_name='driving_records', to='fuel.user'),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='fuel_before_departure',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Количество топлива в баке перед выездом, л (автоматически)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='fuel_on_return',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Остаток топлива в баке при возвращении, л', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='fuel_refueled',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Заправлено топлива за время этой записи, л', max_digits=8),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='fuel_used_area',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Израсходовано топлива по области, л', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='fuel_used_city',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Израсходовано топлива по городу, л', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='fuel_used_total',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Всего израсходовано топлива, л', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='norm_area',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Норма по области, л/км, применённая для этой записи', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='norm_city',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Норма по городу, л/км, применённая для этой записи', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='odometer_after',
            field=models.DecimalField(decimal_places=2, help_text='Показание одометра после возвращения, км', max_digits=7),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='odometer_before',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Показание одометра перед выездом, км (автоматически)', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='passenger_car_waybill',
            field=models.ForeignKey(help_text='Путевой лист легкового автомобиля, к которому относится запись', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='fuel.passengercarwaybill'),
        ),
        migrations.AlterField(
            model_name='passengercarwaybillrecord',
            name='season',
            field=models.CharField(choices=[('winter', 'Зимняя норма'), ('summer', 'Летняя норма')], default='summer', help_text='Какую норму применить для расчёта (зимняя/летняя)', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='driver_license',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='fuel.driverlicense'),
        ),
    ]
