# Generated by Django 6.0.1 on 2026-01-14 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_alter_passengercarwaybillrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='required_role',
            field=models.ForeignKey(help_text='Какую обязательную роль закрывает эта подпись', on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='fuel.requiredrole'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='signed_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда подпись была поставлена'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, который поставил подпись', on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='fuel.user'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='waybill',
            field=models.ForeignKey(help_text='Путевой лист, который подписывается', on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='fuel.waybill'),
        ),
    ]
